services:
  postgresql:
    image: postgres:latest
    container_name: mycommercedb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mycommercedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Campo_Grande
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis-mycommerce
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --loglevel debug --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - default
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - s3_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./predefined-images:/data/images
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;

      /usr/bin/mc mb minio/posts || echo 'Bucket posts already exists';
      /usr/bin/mc mb minio/products || echo 'Bucket products already exists';

      /usr/bin/mc anonymous set public minio/posts;
      /usr/bin/mc anonymous set public minio/products;

      /usr/bin/mc cp /data/images/posts/* minio/posts/ || echo 'Error copying posts';"
      /usr/bin/mc cp /data/images/phones/* minio/products/ || echo 'Error copying images';"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
volumes:
  s3_data:
  redis:
    driver: local
  postgresql:
    driver: local

networks:
  default:
    driver: bridge