name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar SSH para acesso à EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/mykeys.pem
          chmod 600 ~/.ssh/mykeys.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Copiar arquivos para a EC2
      - name: Copy files to EC2
        run: |
          scp -i ~/.ssh/mykeys.pem -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/products

      # Executar Docker Compose na EC2 via SSH
      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/mykeys.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" > .env
            docker compose down --remove-orphans
            docker compose up -d --build
          EOF